require("Util/Common")
require("Util/MissionTask")
require("Util/CP/CP_Common")
require("Util/CP/CP_Func")

multiplayer.objectiveData = {}
chaosMission = true
arenaNum = 3.0
thisArena = "CP_Arena_factory_c"
arenaExit = "mkr_factory_c_exit"
nextArena = "CP_Arena_waterworks"
nextArenaEnter = "mkr_waterworks_enter"

function MissionStartNetwork() --f_0
	InitLuaSafe()
	
	sp_midFloor = COOP_GetSpawnPointGroup("sp_midFloor")
	sp_upperFloor = COOP_GetSpawnPointGroup("sp_upperFloor")
	sp_basement = COOP_GetSpawnPointGroup("sp_basement")
	sp_hallway = COOP_GetSpawnPointGroup("sp_hallway")
	sp_lowFloor = COOP_GetSpawnPointGroup("sp_lowFloor")
	sp_back = COOP_GetSpawnPointGroup("sp_back")
	sp_middle = COOP_GetSpawnPointGroup("sp_middle")
	sp_front = COOP_GetSpawnPointGroup("sp_front")

	sp_wave01_high = {sp_midFloor_01, sp_midFloor_02}
	sp_wave01_low = {sp_back_03,
sp_back_04, sp_hallway_02}
	sp_wave01 = {sp_midFloor_01,
sp_midFloor_02,
sp_back_03,
sp_back_04, sp_hallway_02}
	sp_wave02 = {sp_front_05,
sp_front_03,
sp_hallway_03, sp_front_06}
	sp_wave3 = {sp_basement_01,
sp_back_03,
sp_back_04,
sp_midFloor_04, sp_middle_03}
	sp_wave4 = {sp_midFloor_04,
sp_midFloor_02,
sp_hallway_03,
sp_back_02, sp_back_04}
	sp_wave5 = {sp_midFloor_04,
sp_midFloor_02,
sp_midFloor_03, sp_hallway_03}
	challengeSet1 = {{["challengeType"] = ch_speedKill,
["timeLimit"] = 20.0,
["targetAmount"] = 15.0},
{["challengeType"] = ch_selectiveKill,
["timeLimit"] = 15.0,
["targetAmount"] = 4.0,
["unitType"] = cp_ork_boy_melee_pro},
{["challengeType"] = ch_kingOfTheHill,
["timeLimit"] = 20.0,
["markers"] = {mkr_challengeCP_01},
["captureTime"] = 2.0},
{["challengeType"] = ch_ballHog,
["timeLimit"] = 20.0,
["targetAmount"] = 7.0},
{["challengeType"] = ch_sychronizedKill,
["timeLimit"] = 15.0,
["targetAmount"] = 10.0}}
	challengeSet2 = {{["challengeType"] = ch_speedKill,
["timeLimit"] = 20.0,
["targetAmount"] = 10.0},
{["challengeType"] = ch_selectiveKill,
["timeLimit"] = 15.0,
["targetAmount"] = 5.0,
["unitType"] = cp_ork_boy_ranged_pro},
{["challengeType"] = ch_kingOfTheHill,
["timeLimit"] = 15.0,
["markers"] = {mkr_challengeCP_03},
["captureTime"] = 2.0},
{["challengeType"] = ch_ballHog,
["timeLimit"] = 20.0,
["targetAmount"] = 5.0},
{["challengeType"] = ch_sychronizedKill,
["timeLimit"] = 15.0,
["targetAmount"] = 8.0}}
	challengeSet3 = {{["challengeType"] = ch_speedKill,
["timeLimit"] = 15.0,
["targetAmount"] = 10.0},
{["challengeType"] = ch_kingOfTheHill,
["timeLimit"] = 15.0,
["markers"] = {mkr_challengeCP_05},
["captureTime"] = 2.0},
{["challengeType"] = ch_ballHog,
["timeLimit"] = 15.0,
["targetAmount"] = 6.0},
{["challengeType"] = ch_sychronizedKill,
["timeLimit"] = 15.0,
["targetAmount"] = 8.0}}
	--sp_wave01_high = 12.0
	--sp_wave01_high = 8.0
	--sp_wave01 = 12.0
	--sp_wave01_high = 8.0
	--sp_wave01 = 8.0
	--sp_wave01 = 8.0
	--sp_wave01_high = 8.0
	--sp_wave01_high = 15.0
	wave1 = {{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave01_high,
["aware"] = true},
12.0,
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave01_high,
["aware"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave01_high,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave01_high,
["aware"] = true},
8.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave01_high,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave01_high,
["aware"] = true},
{["leftAlive"] = 10.0},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave01,
["aware"] = true,
["spawnFX"] = true},
12.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_high,
["aware"] = false},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave01_high,
["aware"] = false},
8.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave01_high,
["aware"] = false},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_high,
["aware"] = false},
{["leftAlive"] = 10.0},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave01,
["aware"] = true},
8.0,
{["challenge"] = challengeSet1,
["bonusPoints"] = 2500.0},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave01,
["aware"] = true,
["spawnFX"] = true},
8.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 12.0},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave01_high,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave01_high,
["aware"] = true,
["spawnFX"] = true},
8.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave01_high,
["aware"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave01_high,
["aware"] = true},
{["leftAlive"] = 15.0},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_high,
["aware"] = true},
15.0,
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave01,
["aware"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_high,
["aware"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_high,
["aware"] = true}}
	--sp_front_05 = 1.0
	--sp_front_07 = 3.0
	--sp_wave02 = 5.0
	--sp_wave02 = 5.0
	--sp_wave02 = 5.0
	--sp_wave02 = 5.0
	--sp_hallway_03 = 8.0

	wave2 = {{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_hallway_04,
["goto"] = mkr_capturePoint_Arena,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_sm_dev_lc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_midFloor_03,
["goto"] = sp_front_05},
1.0,
{["ebp"] = cp_guard_guardsman_grenade_launcher,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_front_06,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_front_06,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_front_07,
["spawnFX"] = true},
3.0,
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_midFloor_03,
["spawnFX"] = true},
{["leftAlive"] = 12.0},
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_midFloor_03,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave02,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_wave02,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_grenade_launcher,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave02,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_sm_dev_lc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_midFloor_03,
["spawnFX"] = true},
{["leftAlive"] = 12.0},
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_midFloor_03,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave02,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_wave02,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_grenade_launcher,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave02,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_sm_dev_lc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_midFloor_03,
["spawnFX"] = true},
{["leftAlive"] = 14.0},
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_hallway_03,
["spawnFX"] = true},
8.0,
{["ebp"] = cp_sm_dev_lc,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_midFloor_03,
["spawnFX"] = true}}

-- 	--mkr_squig_goto_04 = 5.0
-- 	--mkr_squig_goto_04 = 5.0
-- 	--sp_wave3 = 5.0
-- 	--challengeSet2 = 15.0
-- 	--sp_midFloor = 5.0
-- 	--sp_midFloor = 5.0
-- 	--sp_midFloor = 10.0
-- 	--sp_midFloor = 5.0
	wave3 = {{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_midFloor_04,
["goto"] = mkr_squig_goto_04,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_back_04,
["goto"] = mkr_squig_goto_04,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_back_02,
["goto"] = mkr_squig_goto_04,
["spawnFX"] = true},
5.0,
networkFunctions.StopAllEnemies,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_lowFloor_01,
["goto"] = mkr_squig_goto_04,
["spawnFX"] = true},
5.0,
networkFunctions.StopAllEnemies,
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave3,
["aware"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave3,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 12.0},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave3,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_wave3,
["aware"] = true,
["spawnFX"] = true},
{["challenge"] = challengeSet2,
["bonusPoints"] = 2500.0},
15.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave3,
["aware"] = true},
{["leftAlive"] = 12.0},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_midFloor,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_midFloor,
["aware"] = false,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_midFloor,
["aware"] = false,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_midFloor,
["aware"] = false},
{["leftAlive"] = 12.0},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_midFloor,
["aware"] = false},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_midFloor,
["aware"] = false},
5.0,
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_midFloor,
["aware"] = false},
{["leftAlive"] = 17.0},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_midFloor,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_midFloor,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_midFloor,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_midFloor,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_midFloor,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 8.0},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave3,
["spawnFX"] = true}}

	--sp_wave4 = 5.0
	--sp_wave4 = 8.0
	--sp_wave4 = 5.0
	--sp_wave4 = 13.0
	--sp_wave4 = 10.0
	--sp_wave4 = 10.0
	--sp_wave4 = 5.0
	--sp_wave4 = 13.0
	--sp_wave4 = 10.0
	--sp_wave4 = 5.0
	--sp_wave4 = 10.0
	--sp_wave4 = 15.0
	wave4loop = {{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true},
8.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true},
13.0,
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave4,
["aware"] = true},
10.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave4,
["aware"] = false,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave4,
["aware"] = false,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave4,
["aware"] = false},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave4,
["aware"] = false},
13.0,
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave4,
["aware"] = false},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave4,
["aware"] = false},
10.0,
{["ebp"] = cp_ork_nob_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true},
15.0}

	--sp_wave4 = 12.0
	wave4 = {{["unitAmount"] = 50.0},
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true},
12.0,
{["capturePoint"] = mkr_capturePoint_Arena,
["awardPoints"] = 2500.0,
["waveBlocker"] = true,
["loopingSpawns"] = wave4loop,
["duration"] = 120.0,
["timeLimit"] = 180.0,
["loseAfterTimeOut"] = true},
1.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave4,
["aware"] = true,
["spawnFX"] = true}}

	--mkr_squig_goto_04 = 3.0
	--sp_wave5 = 4.0
	--sp_wave5 = 4.0
	--sp_wave5 = 5.0
	--sp_middle_05 = 3.0
	--sp_middle_05 = 5.0
	--sp_wave5 = 2.0
	--sp_wave5 = 5.0
	--sp_wave5 = 7.0
	wave5 = {{["ebp"] = cp_sm_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_midFloor_04,
["hold"] = mkr_squig_goto_04,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_sm_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_midFloor_04,
["hold"] = mkr_squig_goto_04,
["aware"] = true,
["spawnFX"] = true},
3.0,
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_back,
["hold"] = mkr_squig_goto_04,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 3.0},
networkFunctions.StopAllEnemies,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave5,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 5.0},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave5,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5,
["aware"] = true,
["spawnFX"] = true},
4.0,
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave5,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5,
["aware"] = true,
["spawnFX"] = true},
4.0,
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave5,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_sm_dev_pc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 12.0},
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_middle_05,
["aware"] = true,
["spawnFX"] = true},
3.0,
{["challenge"] = challengeSet3,
["bonusPoints"] = 2500.0},
{["ebp"] = cp_guard_guardsman_grenade_launcher,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_middle_05,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 7.0,
["spawnPoints"] = sp_middle_05,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_middle_05,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 10.0},
2.0,
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5,
["aware"] = true,
["spawnFX"] = true},
7.0,
{["ebp"] = cp_sm_melee,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5,
["aware"] = true,
["spawnFX"] = true}}

	COOP_RegisterWaves(wave1, wave2, wave3, wave4, wave5)
end

function MissionStart() --f_1
	COOP_StartWaves(trig_start_arena)
	RegisterPlayerEvents()
end

networkFunctions.StopAllEnemies = function () --f_2
	Cmd_Stop(multiplayer.assets._coop_spawnedUnits)
end