require("Util/Common")
require("Util/CP/CP_Common")
require("Util/CP/CP_Func")

multiplayer.objectiveData = {}
chaosMission = true
arenaNum = 2.0
thisArena = "cp_arena_habs_e"
arenaExit = "mkr_habs_e_exit"
nextArena = "CP_Arena_factory_c"
nextArenaEnter = "mkr_factory_c_enter"

function MissionStartNetwork() --f_0
	InitLuaSafe()
	
	sp_ig_defendLast = {sp_wave01_ig_08,
sp_wave01_ig_07,
sp_wave01_ig_06,
sp_wave01_ig_05}
	sp_ig_defendSide = {sp_wave01_ig_01,
sp_wave01_ig_03,
sp_wave01_ig_02,
sp_wave01_ig_10,
sp_wave01_ig_11,
sp_wave03_05}
	sp_wave5_final = {sp_wave01_ig_01,
sp_wave01_ig_03,
sp_wave01_ig_02,
sp_wave01_ig_10,
sp_wave01_ig_11,
sp_wave04_low_02,
sp_wave04_high_04,
sp_wave04_high_05,
sp_wave04_low_01,
sp_wave04_low_04}

	sp_wave03 = COOP_GetSpawnPointGroup("sp_wave03")
	sp_ork_wave03 = COOP_GetSpawnPointGroup("sp_ork_wave03")
	sp_wave04 = COOP_GetSpawnPointGroup("sp_wave04")
	sp_wave04_high = COOP_GetSpawnPointGroup("sp_wave04_high")
	sp_wave04_low = COOP_GetSpawnPointGroup("sp_wave04_low")
	sp_wave05_ork = COOP_GetSpawnPointGroup("sp_wave05_ork")

	challengeSet1 = {{["challengeType"] = ch_speedKill,
["timeLimit"] = 20.0,
["targetAmount"] = 15.0},
{["challengeType"] = ch_selectiveKill,
["timeLimit"] = 20.0,
["targetAmount"] = 4.0,
["unitType"] = cp_ork_hardboy},
{["challengeType"] = ch_kingOfTheHill,
["timeLimit"] = 20.0,
["markers"] = {mkr_capture_02},
["captureTime"] = 2.0},
{["challengeType"] = ch_ballHog,
["timeLimit"] = 20.0,
["targetAmount"] = 8.0},
{["challengeType"] = ch_sychronizedKill,
["timeLimit"] = 20.0,
["targetAmount"] = 8.0}}
	challengeSet2 = {{["challengeType"] = ch_speedKill,
["timeLimit"] = 20.0,
["targetAmount"] = 15.0},
{["challengeType"] = ch_selectiveKill,
["timeLimit"] = 20.0,
["targetAmount"] = 5.0,
["unitType"] = cp_ork_boy_ranged_pro},
{["challengeType"] = ch_kingOfTheHill,
["timeLimit"] = 15.0,
["markers"] = {mkr_capture_02},
["captureTime"] = 2.0},
{["challengeType"] = ch_ballHog,
["timeLimit"] = 20.0,
["targetAmount"] = 8.0},
{["challengeType"] = ch_sychronizedKill,
["timeLimit"] = 20.0,
["targetAmount"] = 8.0}}
	challengeSet3 = {{["challengeType"] = ch_speedKill,
["timeLimit"] = 15.0,
["targetAmount"] = 6.0},
{["challengeType"] = ch_kingOfTheHill,
["timeLimit"] = 15.0,
["markers"] = {mkr_capture_03},
["captureTime"] = 2.0},
{["challengeType"] = ch_ballHog,
["timeLimit"] = 15.0,
["targetAmount"] = 3.0},
{["challengeType"] = ch_sychronizedKill,
["timeLimit"] = 15.0,
["targetAmount"] = 4.0}}

	-- sp_ork_wave03 = 10.0
	-- sp_ork_wave03 = 10.0
	-- sp_ork_wave03 = 15.0
	-- sp_ork_wave03 = 20.0
	Wave3_Loop = {{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave03,
["hold"] = mkr_igcapgoto_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave03,
["hold"] = mkr_igcapgoto_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave03,
["hold"] = mkr_igcapgoto_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_ork_wave03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_ork_wave03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_ork_wave03,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave03,
["hold"] = mkr_igcapgoto_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_grenade_launcher,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave03,
["hold"] = mkr_igcapgoto_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_ork_wave03,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave03,
["hold"] = mkr_igcapgoto_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave03,
["hold"] = mkr_igcapgoto_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave03,
["hold"] = mkr_igcapgoto_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_ork_wave03,
["aware"] = true,
["spawnFX"] = true},
15.0,
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave03,
["hold"] = mkr_igcapgoto_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave03,
["hold"] = mkr_igcapgoto_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave03,
["goto"] = mkr_igcapgoto_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_ork_wave03,
["aware"] = true,
["spawnFX"] = true},
20.0}
	--sp_wave5_final = 5.0
	--sp_wave5_final = 5.0
	--sp_wave5_final = 10.0
	--sp_wave5_final = 5.0
	--sp_wave5_final = 10.0
	--sp_wave5_final = 5.0
	--sp_wave5_final = 15.0
	--sp_wave5_final = 15.0
	Wave5_Loop = {{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_final,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_final,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5_final,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5_final,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave5_final,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave5_final,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_wave5_final,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_sm_dev_pc,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_final,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_sm_dev_pc,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_final,
["aware"] = true,
["spawnFX"] = true},
15.0,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave5_final,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave5_final,
["aware"] = true,
["spawnFX"] = true},
15.0}
	--mkr_hold_RightSide_02 = 3.0
	--mkr_hold_Left_03 = 10.0
	--sp_wave01_orks_13 = 1.0
	wave1 = {{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_orks_02,
["aware"] = true,
["spawnFX"] = true,
["hold"] = mkr_hold_Left_02},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_orks_15,
["aware"] = true,
["spawnFX"] = true,
["hold"] = mkr_hold_Left_03},
{["ebp"] = cp_sm_dev_pc,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave01_ig_02,
["aware"] = true,
["hold"] = mkr_hold_RightSide_01},
{["ebp"] = cp_sm_dev_pc,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave01_ig_01,
["aware"] = true,
["hold"] = mkr_hold_RightSide_02},
3.0,
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_ig_01,
["aware"] = true,
["hold"] = mkr_hold_RightSide_02},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_ig_02,
["aware"] = true,
["hold"] = mkr_hold_RightSide_01},
{["ebp"] = cp_guard_guardsman_grenade_launcher,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_ig_03,
["aware"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave01_orks_01,
["aware"] = true,
["spawnFX"] = true,
["hold"] = mkr_hold_Left_03},
10.0,
{["ebp"] = cp_guard_guardsman_grenade_launcher,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_ig_04,
["aware"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave01_ig_06,
["aware"] = true,
["hold"] = mkr_hold_Up_02},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_orks_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_orks_11,
["aware"] = true,
["spawnFX"] = true,
["hold"] = mkr_hold_Bottom_03},
{["leftAlive"] = 15.0},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave01_orks_14,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave01_orks_13,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave01_ig_05,
["aware"] = true,
["hold"] = mkr_hold_Up_01},
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave01_ig_07,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave01_ig_08,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 12.0},
2.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_orks_02,
["aware"] = true,
["hold"] = mkr_hold_Left_02},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_orks_10,
["aware"] = true,
["hold"] = mkr_hold_Bottom_02},
{["ebp"] = cp_sm_dev_pc,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave01_ig_12,
["aware"] = true},
{["ebp"] = cp_sm_dev_pc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_ig_13,
["aware"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_orks_09,
["aware"] = true,
["hold"] = mkr_hold_Left_01}}
	--mkr_hold_Up_03 = 5.0
	--sp_wave01_ig_01 = 5.0
	--sp_wave01_orks_03 = 5.0
	--sp_wave01_ig_08 = 2.0
	--sp_wave01_orks_13 = 8.0
	wave2 = {5.0,
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave01_ig_05,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_ig_06,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave01_ig_07,
["aware"] = true,
["spawnFX"] = true,
["hold"] = mkr_hold_Up_03},
5.0,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave01_ig_08,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 7.0,
["spawnPoints"] = sp_wave01_ig_01,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave01_ig_03,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 15.0},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave01_orks_14,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave01_orks_13,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave01_orks_06,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave01_orks_03,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave01_ig_07,
["aware"] = true,
["spawnFX"] = true,
["hold"] = mkr_hold_Up_02},
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave01_ig_08,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave01_orks_14,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave01_orks_13,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave01_orks_13,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 15.0},
{["challenge"] = challengeSet1,
["bonusPoints"] = 2000.0},
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave01_ig_06,
["aware"] = true,
["spawnFX"] = true,
["hold"] = mkr_hold_Up_04},
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave01_ig_06,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave01_orks_13,
["aware"] = true,
["spawnFX"] = true},
8.0,
{["ebp"] = cp_sm_dev_pc,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave01_ig_08,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_sm_dev_pc,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave01_ig_07,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_sm_dev_pc,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave01_ig_05,
["aware"] = true,
["spawnFX"] = true}}
	--Wave3_Loop = 90.0
	wave3 = {5.0,
{["capturePoint"] = {mkr_cp_high_01, mkr_capture_02},
["awardPoints"] = 2000.0,
["waveBlocker"] = true,
["loopingSpawns"] = Wave3_Loop,
["duration"] = 90.0,
["timeLimit"] = 180.0,
["loseAfterTimeOut"] = true},
1.0, 
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave01_ig_08,
["aware"] = true}}
	--cp_ork_boy_melee = 15.0
	--cp_ork_boy_melee_pro = 15.0
	--cp_ork_hardboy = 5.0
	--cp_ork_nob_melee = 2.0
	--challengeSet2 = 2000.0
	--cp_ork_boy_ranged_pro = 5.0
	--cp_ork_boy_ranged_pro = 5.0
	--cp_ork_nob_melee = 3.0
	--cp_ork_nob_shoota = 4.0
	--cp_ork_nob_melee = 4.0
	wave4 = {{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 15.0,
["spawnPoints"] = sp_wave04,
["aware"] = true,
["spawnFX"] = true},
15.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 15.0,
["spawnPoints"] = sp_wave04,
["aware"] = true,
["spawnFX"] = true},
15.0,
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave04,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_nob_melee,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave04,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 17.0},
{["challenge"] = challengeSet2,
["bonusPoints"] = 2000.0},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave04_high,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave04_high,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_nob_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave04_low,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 12.0},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave04_high,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave04_low,
["aware"] = true,
["spawnFX"] = true}}

	--cp_sm_chainsword = 2.0
	--cp_ork_nob_melee = 2.0
	--cp_ork_boy_melee = 2.0
	--cp_ork_boy_melee = 2.0
	--cp_ork_boy_melee = 2.0
	--cp_sm_chainsword = 2.0
	--cp_sm_bolter = 1.0
	--challengeSet3 = 2000.0
	--challengeSet3 = 2.0
	--cp_sm_chainsword = 1.0
	--cp_sm_chainsword = 1.0
	--cp_sm_bolter = 1.0
	--cp_sm_bolter = 1.0
	--cp_sm_chainsword = 1.0
	--cp_sm_chainsword = 1.0
	--cp_sm_dev_pc = 1.0
	--mkr_capture_01 = 2000.0
	--Wave5_Loop = 90.0
	wave5 = {{["unitAmount"] = 32.0},
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_ig_defendSide,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave05_ork,
["aware"] = true,
["spawnFX"] = true},
3.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave05_ork,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave05_ork,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave05_ork,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_ig_defendSide,
["aware"] = true,
["spawnFX"] = true},
8.0,
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_ig_defendSide,
["aware"] = true,
["spawnFX"] = true},
{["challenge"] = challengeSet3,
["bonusPoints"] = 2000.0},
2.0,
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_ig_defendSide,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_ig_defendSide,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_ig_defendLast,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_ig_defendLast,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 4.0},
2.0,
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_ig_defendLast,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_ig_defendLast,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_sm_dev_pc,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_ig_defendLast,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 4.0},
{["capturePoint"] = mkr_capture_01,
["awardPoints"] = 2000.0,
["waveBlocker"] = true,
["loopingSpawns"] = Wave5_Loop,
["duration"] = 90.0,
["timeLimit"] = 180.0,
["loseAfterTimeOut"] = true},
1.0, 
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave01_ig_08,
["aware"] = true}}
	COOP_RegisterWaves(wave1, wave2, wave3, wave4, wave5)
end

function MissionStart() --f_1
	COOP_StartWaves(trig_start)
	RegisterPlayerEvents()
end

networkFunctions.stopIG = function () --f_2
	Cmd_Stop(multiplayer.assets._coop_spawnedUnits)
end