Group_SpawnEntities(grp_dropship, "ebps\\props\\enemy_console", sp_entrance_pipe, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_ork_killa_kan.bp, sp_wbWave_06, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_ork_gretchin.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_ork_boy_melee.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_ork_boy_melee.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_ork_boy_ranged_grenade.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_ork_boy_ranged_pro.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_ork_nob_shoota.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_ork_boy_melee_pro.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_ork_hardboy.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_ork_nob_melee.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_ork_squig_bomb.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_ork_nob_shoota_pro.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_ork_nob_melee_pro.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_guard_guardsman.bp, sp_wbWave_06, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_guard_guardsman_grenade_launcher.bp, sp_wbWave_06, 1.0)	
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_guard_guardsman_shotgun.bp, sp_wbWave_06, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_guard_guardsman_chainsword.bp, sp_wbWave_06, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_guard_psyker.bp, sp_wbWave_06, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_sm_bolter.bp, sp_wbWave_06, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_sm_dev_pc.bp, sp_wbWave_06, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_sm_dev_lc.bp, sp_wbWave_06, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_sm_chainsword.bp, sp_wbWave_06, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_sm_melee.bp, sp_wbWave_06, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_guard_guardsman.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, 'ebps\\multiplayer\\race_assassins\\callidus', sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, 'ebps\\multiplayer\\race_chaos\\chaos_drone', sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, 'ebps\\multiplayer\\race_guard\\ig_coop_guardsman_chainsword', sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, 'ebps\\multiplayer\\race_ork\\ork_coop_warboss', sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, chaos_coop_renegade_ig.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, chaos_coop_renegade_ig_glauncher.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, chaos_coop_renegade_ig_melta.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, chaos_coop_renegade_ig_melee.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, chaos_coop_renegade_ig_spawn_bl.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_chaos_bloodletter.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_chaos_tainted_psyker.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_chaos_marine_bolter.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_chaos_marine_havok_pc.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, chaos_coop_marine_havok_lc.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, chaos_coop_marine_chainsword.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, cp_chaos_marine_melee.bp, sp_middle_01, 1.0)
Group_SpawnEntities(multiplayer.assets.grp_currentWave, chaos_coop_renegade_ig.bp, sp_middle_01, 1.0)
Group_SpawnAttached(grp_dropship, "ebps\\multiplayer\\common\\sm_banner", Player_GetEntity(Player_GetLocal()), "rig_spined", "rig_root", "")

COOP_RequestSpawn(monolith, POS(-558.1, 21.53, 17.88), nil, nil, true, Group_Create(""), true, true)
COOP_RequestSpawn(necron_warrior, tdm_mkr_spawn_01, nil, nil, true, Group_Create(""), true, true)