require("Util/Common")
require("Util/CP/CP_Common")
require("Util/CP/CP_Func")

multiplayer.objectiveData = {}
arenaNum = 4.0
thisArena = "cp_arena_habs_c"
arenaExit = "mkr_habs_c_exit"

function MissionStartNetwork() --f_0
	InitLuaSafe()
	
	sp_left = COOP_GetSpawnPointGroup("sp_left")
	sp_right = COOP_GetSpawnPointGroup("sp_right")
	sp_middle = COOP_GetSpawnPointGroup("sp_middle")
	sp_top = COOP_GetSpawnPointGroup("sp_top")

	Coop_SetLayerLightsEnabled("L_Lights_Chaos", false)

	challengeSet1 = {
		{["challengeType"] = ch_speedKill,
		["timeLimit"] = 15.0,
		["targetAmount"] = 10.0},
		{["challengeType"] = ch_selectiveKill,
		["timeLimit"] = 20.0,
		["targetAmount"] = 10.0,
		["unitType"] = cp_ork_boy_melee},
		{["challengeType"] = ch_ballHog,
		["timeLimit"] = 25.0,
		["targetAmount"] = 10.0},
		{["challengeType"] = ch_sychronizedKill,
		["timeLimit"] = 25.0,
		["targetAmount"] = 5.0}
	}

	challengeSet2 = {
		{["challengeType"] = ch_selectiveKill,
		["timeLimit"] = 25.0,
		["targetAmount"] = 15.0,
		["unitType"] = cp_ork_boy_melee_pro},
		{["challengeType"] = ch_dreadnought,
		["timeLimit"] = 15.0,
		["markers"] = mkr_objective_02,
		["captureTime"] = 2.0},
		{["challengeType"] = ch_dreadnought,
		["timeLimit"] = 15.0,
		["markers"] = mkr_objective_08,
		["captureTime"] = 2.0},
		{["challengeType"] = ch_sychronizedKill,
		["timeLimit"] = 20.0,
		["targetAmount"] = 5.0}
	}

	challengeSet3 = {
		{["challengeType"] = ch_selectiveKill,
		["timeLimit"] = 20.0,
		["targetAmount"] = 5.0,
		["unitType"] = cp_ork_hardboy},
		{["challengeType"] = ch_dreadnought,
		["timeLimit"] = 15.0,
		["markers"] = mkr_objective_09,
		["captureTime"] = 2.0},
		{["challengeType"] = ch_dreadnought,
		["timeLimit"] = 15.0,
		["markers"] = mkr_objective_10,
		["captureTime"] = 2.0},
		{["challengeType"] = ch_multiMegaKill,
		["timeLimit"] = 20.0,
		["targetAmount"] = 5.0}
	}

	wave2loop = {
		5.0,
		{["ebp"] = cp_ork_boy_ranged_grenade,
		["unitAmount"] = 5.0,
		["spawnPoints"] = sp_left_01,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_boy_ranged_grenade,
		["unitAmount"] = 5.0,
		["spawnPoints"] = sp_right_01,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_boy_melee,
		["unitAmount"] = 20.0,
		["spawnPoints"] = sp_middle,
		["aware"] = true,
		["spawnFX"] = true},
		8.0,
		{["ebp"] = cp_ork_boy_ranged_pro,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_top_right,
		["goto"] = mkr_right_01,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_boy_ranged_grenade,
		["unitAmount"] = 3.0,
		["spawnPoints"] = sp_top_right,
		["goto"] = mkr_right_01,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_boy_ranged_pro,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_top_left,
		["goto"] = mkr_left_01,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_boy_ranged_grenade,
		["unitAmount"] = 3.0,
		["spawnPoints"] = sp_top_left,
		["goto"] = mkr_left_01,
		["aware"] = true,
		["spawnFX"] = true},
		6.0,
		{["ebp"] = cp_ork_boy_melee,
		["unitAmount"] = 8.0,
		["spawnPoints"] = sp_orks_start,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_boy_melee,
		["unitAmount"] = 8.0,
		["spawnPoints"] = sp_left_03,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_boy_melee_pro,
		["unitAmount"] = 6.0,
		["spawnPoints"] = sp_middle_02,
		["aware"] = true,
		["spawnFX"] = true},
		10.0,
		{["ebp"] = cp_ork_boy_ranged_pro,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_top_right,
		["goto"] = mkr_right_02,
		["aware"] = true},
		{["ebp"] = cp_ork_boy_ranged_grenade,
		["unitAmount"] = 3.0,
		["spawnPoints"] = sp_top_right,
		["goto"] = mkr_right_03,
		["aware"] = true},
		{["ebp"] = cp_ork_boy_ranged_pro,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_top_right,
		["goto"] = mkr_right_02,
		["aware"] = true},
		{["ebp"] = cp_ork_boy_ranged_grenade,
		["unitAmount"] = 3.0,
		["spawnPoints"] = sp_top_right,
		["goto"] = mkr_right_03,
		["aware"] = true},
		{["ebp"] = cp_ork_squig_bomb,
		["unitAmount"] = 2.0,
		["spawnPoints"] = sp_middle_02,
		["aware"] = true},
		10.0,
		{["ebp"] = cp_ork_hardboy,
		["unitAmount"] = 6.0,
		["spawnPoints"] = sp_middle,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_boy_ranged_grenade,
		["unitAmount"] = 6.0,
		["spawnPoints"] = sp_middle,
		["aware"] = true,
		["spawnFX"] = true},
		10.0,
		{["ebp"] = cp_ork_boy_melee,
		["unitAmount"] = 5.0,
		["spawnPoints"] = sp_right_03,
		["aware"] = true},
		{["ebp"] = cp_ork_boy_melee,
		["unitAmount"] = 5.0,
		["spawnPoints"] = sp_left_03,
		["aware"] = true},
		{["ebp"] = cp_ork_boy_melee_pro,
		["unitAmount"] = 3.0,
		["spawnPoints"] = sp_orks_start_02,
		["aware"] = true},
		{["ebp"] = cp_ork_boy_melee_pro,
		["unitAmount"] = 3.0,
		["spawnPoints"] = sp_orks_start_01,
		["aware"] = true},
		{["ebp"] = cp_ork_nob_melee_pro,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_right_03,
		["aware"] = true},
		{["ebp"] = cp_ork_nob_melee_pro,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_left_03,
		["aware"] = true},
		5.0,
		{["ebp"] = cp_ork_nob_melee_pro,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_left_01,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_nob_melee_pro,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_right_01,
		["aware"] = true,
		["spawnFX"] = true},
		5.0,
		{["ebp"] = cp_ork_squig_bomb,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_orks_start_01,
		["aware"] = true},
		{["ebp"] = cp_ork_squig_bomb,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_left_02,
		["aware"] = true},
		{["ebp"] = cp_ork_squig_bomb,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_right_01,
		["aware"] = true},
		{["ebp"] = cp_ork_squig_bomb,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_right_02,
		["aware"] = true}
	}

	wave3loop = {5.0,
		{["ebp"] = cp_ork_boy_ranged_grenade,
		["unitAmount"] = 3.0,
		["spawnPoints"] = sp_left_03,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_boy_ranged_pro,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_left_03,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_boy_ranged_grenade,
		["unitAmount"] = 3.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		{["ebp"] = cp_ork_boy_ranged_pro,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		{["ebp"] = cp_ork_boy_melee,
		["unitAmount"] = 5.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		{["ebp"] = cp_ork_boy_melee_pro,
		["unitAmount"] = 5.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		{["ebp"] = cp_ork_boy_melee,
		["unitAmount"] = 5.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		{["ebp"] = cp_ork_boy_melee_pro,
		["unitAmount"] = 5.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		8.0,
		{["ebp"] = cp_ork_boy_melee_pro,
		["unitAmount"] = 8.0,
		["spawnPoints"] = sp_middle,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_nob_shoota_pro,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_top_left,
		["goto"] = mkr_left_02,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_boy_ranged_pro,
		["unitAmount"] = 2.0,
		["spawnPoints"] = sp_left,
		["aware"] = true,
		["spawnFX"] = true},
		5.0,
		{["ebp"] = cp_ork_squig_bomb,
		["unitAmount"] = 2.0,
		["spawnPoints"] = sp_left,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_squig_bomb,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_left_01,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_squig_bomb,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_left_02,
		["aware"] = true},
		{["ebp"] = cp_ork_squig_bomb,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_right_01,
		["aware"] = true},
		{["ebp"] = cp_ork_squig_bomb,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_right_02,
		["aware"] = true},
		1.0,
		{["ebp"] = cp_ork_boy_ranged_grenade,
		["unitAmount"] = 3.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		{["ebp"] = cp_ork_boy_ranged_grenade,
		["unitAmount"] = 4.0,
		["spawnPoints"] = sp_top_left,
		["goto"] = mkr_left_01,
		["aware"] = true},
		{["ebp"] = cp_ork_nob_shoota_pro,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		5.0,
		{["ebp"] = cp_ork_squig_bomb,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		10.0,
		{["ebp"] = cp_ork_boy_ranged_pro,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_top_left,
		["goto"] = mkr_left_02,
		["aware"] = false},
		{["ebp"] = cp_ork_boy_ranged_grenade,
		["unitAmount"] = 2.0,
		["spawnPoints"] = sp_top_left,
		["goto"] = mkr_left_02,
		["aware"] = false},
		{["ebp"] = cp_ork_boy_ranged_grenade,
		["unitAmount"] = 2.0,
		["spawnPoints"] = sp_top_left,
		["goto"] = mkr_left_01,
		["aware"] = false},
		{["ebp"] = cp_ork_boy_ranged_pro,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_top_left,
		["goto"] = mkr_left_01,
		["aware"] = false},
		{["ebp"] = cp_ork_nob_shoota_pro,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_top_left,
		["goto"] = mkr_left_03,
		["aware"] = false},
		12.0,
		{["ebp"] = cp_ork_nob_shoota_pro,
		["unitAmount"] = 2.0,
		["spawnPoints"] = sp_middle,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_boy_ranged_grenade,
		["unitAmount"] = 4.0,
		["spawnPoints"] = sp_middle,
		["aware"] = true,
		["spawnFX"] = true},
		10.0,
		{["ebp"] = cp_ork_hardboy,
		["unitAmount"] = 2.0,
		["spawnPoints"] = sp_right_03,
		["aware"] = true},
		{["ebp"] = cp_ork_hardboy,
		["unitAmount"] = 2.0,
		["spawnPoints"] = sp_right,
		["aware"] = true},
		{["ebp"] = cp_ork_boy_melee_pro,
		["unitAmount"] = 8.0,
		["spawnPoints"] = sp_right_03,
		["aware"] = true},
		{["ebp"] = cp_ork_boy_melee_pro,
		["unitAmount"] = 8.0,
		["spawnPoints"] = sp_right,
		["aware"] = true},
		5.0,
		{["ebp"] = cp_ork_boy_melee_pro,
		["unitAmount"] = 2.0,
		["spawnPoints"] = sp_middle,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_boy_melee_pro,
		["unitAmount"] = 2.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		{["ebp"] = cp_ork_hardboy,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_middle,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_hardboy,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		8.0,
		{["ebp"] = cp_ork_squig_bomb,
		["unitAmount"] = 2.0,
		["spawnPoints"] = sp_middle,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_squig_bomb,
		["unitAmount"] = 2.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		10.0,
		{["ebp"] = cp_ork_boy_ranged_pro,
		["unitAmount"] = 3.0,
		["spawnPoints"] = sp_middle,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_boy_ranged_pro,
		["unitAmount"] = 2.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		15.0,
		{["ebp"] = cp_ork_hardboy,
		["unitAmount"] = 2.0,
		["spawnPoints"] = sp_left,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_boy_melee_pro,
		["unitAmount"] = 8.0,
		["spawnPoints"] = sp_left,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_nob_melee_pro,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_left,
		["aware"] = true,
		["spawnFX"] = true},
		15.0,
		{["ebp"] = cp_ork_hardboy,
		["unitAmount"] = 2.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		{["ebp"] = cp_ork_nob_shoota_pro,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		{["ebp"] = cp_ork_boy_melee,
		["unitAmount"] = 3.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		{["ebp"] = cp_ork_nob_shoota_pro,
		["unitAmount"] = 1.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		12.0,
		{["ebp"] = cp_ork_squig_bomb,
		["unitAmount"] = 2.0,
		["spawnPoints"] = sp_middle,
		["aware"] = true,
		["spawnFX"] = true},
		{["ebp"] = cp_ork_squig_bomb,
		["unitAmount"] = 2.0,
		["spawnPoints"] = sp_middle,
		["aware"] = true,
		["spawnFX"] = true},
		12.0,
		{["ebp"] = cp_ork_boy_melee_pro,
		["unitAmount"] = 8.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		{["ebp"] = cp_ork_boy_melee_pro,
		["unitAmount"] = 8.0,
		["spawnPoints"] = sp_left,
		["aware"] = true},
		12.0,
		{["ebp"] = cp_ork_nob_melee_pro,
		["unitAmount"] = 2.0,
		["spawnPoints"] = sp_middle,
		["aware"] = true,
		["spawnFX"] = true}}

	wave4loop = {5.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_orks_start_02,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_orks_start_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 12.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
3.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_middle_02,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_orks_start_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_orks_start_02,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
15.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
15.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_orks_start_02,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_orks_start_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_right,
["aware"] = true},
15.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_02,
["aware"] = false,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_02,
["aware"] = false,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_01,
["aware"] = false,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_01,
["aware"] = false,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_03,
["aware"] = false,
["spawnFX"] = true},
15.0,
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_orks_start_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_orks_start_02,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_orks_start_02,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_orks_start_01,
["aware"] = true,
["spawnFX"] = true}}

	wave1 = {2.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_orks_start,
["aware"] = true},
3.0,
2.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_left_01,
["aware"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_left_02,
["aware"] = true},
1.0,
4.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_right_01,
["aware"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_right_02,
["aware"] = true},
8.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_right_03,
["aware"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_left_03,
["aware"] = true},
{["leftAlive"] = 10.0},
10.0,
5.0,
1.0,
4.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_right_03,
["aware"] = true},
3.0,
2.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_left_03,
["aware"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_left,
["aware"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_right,
["aware"] = true},
10.0,
3.0,
1.0,
2.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_left,
["aware"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_left,
["aware"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_left,
["aware"] = true},
1.0,
{["leftAlive"] = 10.0},
5.0,
1.0,
4.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["challenge"] = challengeSet1,
["bonusPoints"] = 2500.0},
12.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_left,
["aware"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_middle,
["aware"] = true}}

	wave2 = {5.0,
{["capturePoint"] = {mkr_objective_01, mkr_objective_05},
["awardPoints"] = 2500.0,
["waveBlocker"] = true,
["loopingSpawns"] = wave2loop,
["duration"] = 90.0,
["timeLimit"] = 150.0,
["loseAfterTimeOut"] = true},
1.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_middle,
["aware"] = true}}

	wave3 = {10.0,
	networkFunctions.StopShowWayLeft,
1.0,
networkFunctions.ShowWayLeft,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_left_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_left,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_left,
["aware"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_left,
["aware"] = true},
8.0,
{["leftAlive"] = 20.0},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_02,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_left,
["aware"] = true},
5.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_left,
["aware"] = true},
1.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_left,
["aware"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_left,
["aware"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_01,
["aware"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_01,
["aware"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_left,
["aware"] = true},
5.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_left,
["aware"] = true},
{["leftAlive"] = 10.0},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_02,
["aware"] = false},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_02,
["aware"] = false},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_01,
["aware"] = false},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_01,
["aware"] = false},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_03,
["aware"] = false},
8.0,
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
8.0,
5.0,
1.0,
4.0,
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_right_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_right,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_right_03,
["aware"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_right,
["aware"] = true},
2.0,
{["challenge"] = challengeSet3,
["bonusPoints"] = 2500.0},
5.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_left,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_left,
["aware"] = true,
["spawnFX"] = true},
8.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
--nil,
{["leftAlive"] = 15.0},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_left,
["aware"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_left,
["aware"] = true},
10.0,
3.0,
1.0,
2.0,
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_left,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_left,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_left,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_left,
["aware"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_left,
["aware"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_left,
["aware"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_left,
["aware"] = true},
12.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
12.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_left,
["aware"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_left,
["aware"] = true},
12.0,
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_left,
["aware"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_right,
["aware"] = true}}

	wave4 = {5.0,
{["capturePoint"] = {mkr_objective_06, mkr_objective_07},
["awardPoints"] = 2500.0,
["waveBlocker"] = true,
["loopingSpawns"] = wave4loop,
["duration"] = 90.0,
["timeLimit"] = 150.0,
["loseAfterTimeOut"] = true},
1.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
3.0,
{["challenge"] = challengeSet2,
["bonusPoints"] = 2500.0},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_middle_02,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
15.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
15.0,
5.0,
1.0,
4.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_right,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_right,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_right,
["aware"] = true},
15.0,
3.0,
1.0,
2.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_02,
["aware"] = false,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_02,
["aware"] = false,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_01,
["aware"] = false},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_01,
["aware"] = false},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_03,
["aware"] = false},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_top_left,
["goto"] = mkr_left_03,
["aware"] = false},
15.0,
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true}}

	wave5 = {10.0,
	networkFunctions.StopShowWayRight,
1.0,
networkFunctions.ShowWayRight,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 12.0,
["spawnPoints"] = sp_right,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_right,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_right,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_right,
["aware"] = true},
10.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_right,
["aware"] = true},
2.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["leftAlive"] = 10.0},
10.0,
networkFunctions.StopShowWayLeft,
1.0,
networkFunctions.ShowWayLeft,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_left,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_left,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_left,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_right,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_middle,
["aware"] = true},
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_middle,
["aware"] = true},
10.0,
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 10.0},
10.0,
networkFunctions.StopShowWayRight,
1.0,
networkFunctions.ShowWayRight,
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_right,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_right,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_right,
["aware"] = true},
10.0,
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_right,
["aware"] = true},
10.0,
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_left,
["aware"] = true,
["spawnFX"] = true},
--nil,
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_left,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_top_left,
["aware"] = true,
["spawnFX"] = true}}

	wave6 = {5.0,
networkFunctions.startChaos,
5.0,
networkFunctions.ChaosPortalsMid,
5.0,
{["ebp"] = cp_chaos_marine_havok_pc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_top_left,
["aware"] = true},
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_chaos_marine_bolter,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_middle_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_chaos_marine_bolter,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_middle_03,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_chaos_marine_bolter,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_middle_02,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_chaos_marine_bolter,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_middle_01,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 10.0},
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_middle_03,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_chaos_marine_melee,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
2.0,
networkFunctions.ChaosEnd,
2.0,
networkFunctions.ChaosPortalsLeft,
5.0,
{["ebp"] = cp_chaos_marine_havok_pc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_top_left,
["aware"] = true},
15.0,
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_left_03,
["aware"] = true},
{["leftAlive"] = 15.0},
10.0,
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_left_03,
["aware"] = true},
{["ebp"] = cp_chaos_marine_bolter,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_left_01,
["aware"] = true},
10.0,
{["ebp"] = cp_chaos_marine_bolter,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_left_03,
["aware"] = true},
10.0,
{["ebp"] = cp_chaos_marine_havok_pc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_left,
["aware"] = true},
{["leftAlive"] = 15.0},
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_left_03,
["aware"] = true},
{["ebp"] = cp_chaos_marine_havok_pc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_left_03,
["aware"] = true},
2.0,
networkFunctions.ChaosEnd,
2.0,
networkFunctions.ChaosPortalsRight,
5.0,
{["ebp"] = cp_chaos_marine_bolter,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_top_right,
["aware"] = true},
--nil,
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_right,
["aware"] = true},
10.0,
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_chaos_marine_bolter,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_right_03,
["aware"] = true},
{["ebp"] = cp_chaos_marine_bolter,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_right_03,
["aware"] = true},
15.0,
{["ebp"] = cp_chaos_marine_havok_pc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_top_right,
["aware"] = true},
15.0,
{["leftAlive"] = 6.0},
{["ebp"] = cp_chaos_marine_bolter,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_right_03,
["aware"] = true},
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_chaos_marine_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_right_03,
["aware"] = true},
2.0,
networkFunctions.ChaosEnd,
2.0,
networkFunctions.ChaosPortalsMid,
5.0,
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_chaos_marine_bolter,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_middle_03,
["aware"] = true,
["spawnFX"] = true},
10.0,
networkFunctions.ChaosPortalsRight,
5.0,
{["ebp"] = cp_chaos_marine_havok_pc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_chaos_marine_havok_pc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_top_right,
["aware"] = true},
{["ebp"] = cp_chaos_marine_havok_pc,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_middle_03,
["aware"] = true,
["spawnFX"] = true},
15.0,
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_chaos_marine_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_chaos_marine_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_chaos_marine_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["ebp"] = cp_chaos_marine_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_right,
["aware"] = true},
{["leftAlive"] = 5.0},
2.0,
networkFunctions.ChaosPortalsLeft,
2.0,
{["ebp"] = cp_chaos_marine_havok_pc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_top_left,
["aware"] = true},
{["ebp"] = cp_chaos_marine_havok_pc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_top_right,
["aware"] = true},
5.0,
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 9.0,
["spawnPoints"] = sp_left,
["aware"] = true},
10.0,
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 9.0,
["spawnPoints"] = sp_left,
["aware"] = true},
10.0,
--nil,
{["ebp"] = cp_chaos_marine_bolter,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_top_left,
["aware"] = true},
{["leftAlive"] = 10.0},
10.0,
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_left_03,
["aware"] = true},
{["ebp"] = cp_chaos_marine_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_left_03,
["aware"] = true},
10.0,
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_right_03,
["aware"] = true},
{["ebp"] = cp_chaos_marine_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_right_03,
["aware"] = true},
10.0,
{["leftAlive"] = 8.0},
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_chaos_bloodletter,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_chaos_marine_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_chaos_marine_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_chaos_marine_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_middle,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_chaos_marine_havok_pc,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_top_left,
["aware"] = true},
{["ebp"] = cp_chaos_marine_havok_pc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_top_left,
["aware"] = true},
{["ebp"] = cp_chaos_marine_havok_pc,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_top_left,
["aware"] = true},
5.0,
networkFunctions.ChaosEnd}

	COOP_RegisterWaves(wave1, wave2, wave3, wave4, wave5, wave6)
end

function MissionStart() --f_1
	Coop_SetWorldObjectVisible("sky_chaos", false)
	COOP_StartWaves(trig_start)
	RegisterPlayerEvents()
end

networkFunctions.ShowWayLeft = function () --f_2
	Marker_PlayFX(mkr_explosionWay_01_Left)
	Marker_PlayFX(mkr_explosionWay_02_Left)
end

networkFunctions.StopShowWayLeft = function () --f_3
	Marker_StopFX(mkr_explosionWay_01_Left)
	Marker_StopFX(mkr_explosionWay_02_Left)
end

networkFunctions.ShowWayRight = function () --f_4
	Marker_PlayFX(mkr_explosionWay_01_Right)
	Marker_PlayFX(mkr_explosionWay_02_Right)
end

networkFunctions.StopShowWayRight = function () --f_5
	Marker_StopFX(mkr_explosionWay_01_Right)
	Marker_StopFX(mkr_explosionWay_02_Right)
end

networkFunctions.startChaos = function () --f_6
	Coop_SetWorldObjectVisible("sky_chaos", true)
	Coop_SetWorldObjectVisible("sky_day", false)
	World_EnvironmentRegionSetEnabled("_globalEnvReg_Chaos", true)
	World_EnvironmentRegionSetEnabled("globalEnvReg_Sunset", false)
	Coop_SetLayerLightsEnabled("L_Lights_Beginning", false)
	Coop_SetLayerLightsEnabled("L_Lights_Chaos", true)
	Coop_SetLayerFXEnabled("L_Lights_Beginning", false)
	Marker_PlayFX(warp_gate_huge)
end

networkFunctions.ChaosPortalsMid = function () --f_7
	Marker_PlayFX(fx_portal_09)
	Marker_PlayFX(fx_portal_01)
	Marker_PlayFX(fx_portal_02)
end

networkFunctions.ChaosPortalsLeft = function () --f_8
	Marker_PlayFX(fx_portal_03)
	Marker_PlayFX(fx_portal_05)
	Marker_PlayFX(fx_portal_07)
end

networkFunctions.ChaosPortalsRight = function () --f_9
	Marker_PlayFX(fx_portal_04)
	Marker_PlayFX(fx_portal_06)
	Marker_PlayFX(fx_portal_08)
end

networkFunctions.ChaosEnd = function () --f_10
	Marker_StopFX(fx_portal_01)
	Marker_StopFX(fx_portal_02)
	Marker_StopFX(fx_portal_03)
	Marker_StopFX(fx_portal_04)
	Marker_StopFX(fx_portal_05)
	Marker_StopFX(fx_portal_06)
	Marker_StopFX(fx_portal_07)
	Marker_StopFX(fx_portal_08)
end