require("Util/Common")
require("Util/Scarutil")
require("Util/CP/CP_Common")
require("Util/CP/CP_AutomatedTurrets")
require("Util/CP/CP_Func")

multiplayer.assets.csp_firing = nil
multiplayer.objectiveData = {
}
arenaNum = 1.0
thisArena = "cp_arena_labs_d"
arenaExit = "mkr_labs_d_exit"
nextArena = "cp_arena_labs_a"
nextArenaEnter = "mkr_labs_a_entrance"

function MissionStartNetwork() --f_0
	InitLuaSafe()
	
	sp_north_01 = {sp_wave1_04}
	sp_north_02 = {sp_wave1_03}
	sp_wave1 = COOP_GetSpawnPointGroup("sp_wave1_01")
    sp_wave1_near = COOP_GetSpawnPointGroup("sp_wave1_02")
    sp_wave1_far = COOP_GetSpawnPointGroup("sp_wave1_04")
    sp_wave_after = COOP_GetSpawnPointGroup("sp_wave1_03")
    sp_wave_after_02 = COOP_GetSpawnPointGroup("sp_wave1_05")
    sp_wave2 = COOP_GetSpawnPointGroup("sp_wave2_05")
    sp_wave2_01 = COOP_GetSpawnPointGroup("sp_wave2_06")
    sp_wave2_mid = COOP_GetSpawnPointGroup("sp_wave2_04")
    sp_wave2_back = COOP_GetSpawnPointGroup("sp_wave2_03")
    sp_wave2_back_02 = COOP_GetSpawnPointGroup("sp_wave2_07")
    sp_wave3 = COOP_GetSpawnPointGroup("sp_wave3_02")
    sp_wave3_02 = COOP_GetSpawnPointGroup("sp_wave3_01")
    sp_wave3_03 = COOP_GetSpawnPointGroup("sp_wave3_03")
    sp_wave4 = COOP_GetSpawnPointGroup("sp_wave4_01")
    sp_wave4_02 = COOP_GetSpawnPointGroup("sp_wave4_02")
    sp_wave4_03 = COOP_GetSpawnPointGroup("sp_wave4_03")
    sp_wave4_04 = COOP_GetSpawnPointGroup("sp_wave4_04")
    sp_wave5 = COOP_GetSpawnPointGroup("sp_wave5_01")
    sp_wave5_02 = COOP_GetSpawnPointGroup("sp_wave5_02")
    sp_wave5_03 = COOP_GetSpawnPointGroup("sp_wave5_03")
    sp_wave5_04 = COOP_GetSpawnPointGroup("sp_wave5_04")
    sp_wave5_05 = COOP_GetSpawnPointGroup("sp_wave5_05")
    sp_wave5_06 = COOP_GetSpawnPointGroup("sp_wave5_06")
		
	challengeSet1 = {{["challengeType"] = ch_speedKill,
["timeLimit"] = 15.0,
["targetAmount"] = 10.0},
{["challengeType"] = ch_selectiveKill,
["timeLimit"] = 20.0,
["targetAmount"] = 8.0,
["unitType"] = cp_ork_gretchin},
{["challengeType"] = ch_selectiveKill,
["timeLimit"] = 15.0,
["targetAmount"] = 2.0,
["unitType"] = cp_ork_boy_ranged},
{["challengeType"] = ch_ballHog,
["timeLimit"] = 15.0,
["targetAmount"] = 5.0},
{["challengeType"] = ch_sychronizedKill,
["timeLimit"] = 15.0,
["targetAmount"] = 5.0},
{["challengeType"] = ch_multiMegaKill,
["timeLimit"] = 15.0,
["targetAmount"] = 3.0}}

	challengeSet2 = {{["challengeType"] = ch_speedKill,
["timeLimit"] = 15.0,
["targetAmount"] = 10.0},
{["challengeType"] = ch_selectiveKill,
["timeLimit"] = 20.0,
["targetAmount"] = 4.0,
["unitType"] = cp_ork_boy_ranged_pro},
{["challengeType"] = ch_selectiveKill,
["timeLimit"] = 20.0,
["targetAmount"] = 5.0,
["unitType"] = cp_ork_boy_melee},
{["challengeType"] = ch_ballHog,
["timeLimit"] = 15.0,
["targetAmount"] = 5.0},
{["challengeType"] = ch_sychronizedKill,
["timeLimit"] = 15.0,
["targetAmount"] = 5.0}}

	challengeSet3 = {{["challengeType"] = ch_speedKill,
["timeLimit"] = 20.0,
["targetAmount"] = 10.0},
{["challengeType"] = ch_selectiveKill,
["timeLimit"] = 20.0,
["targetAmount"] = 15.0,
["unitType"] = cp_ork_gretchin},
{["challengeType"] = ch_selectiveKill,
["timeLimit"] = 20.0,
["targetAmount"] = 10.0,
["unitType"] = cp_ork_boy_melee},
{["challengeType"] = ch_ballHog,
["timeLimit"] = 15.0,
["targetAmount"] = 5.0},
{["challengeType"] = ch_sychronizedKill,
["timeLimit"] = 15.0,
["targetAmount"] = 5.0},
{["challengeType"] = ch_kingOfTheHill,
["timeLimit"] = 20.0,
["markers"] = {mkr_challengeCP_03},
["captureTime"] = 2.0}}

	--sp_mid_03 = 1.0
	--sp_mid_02 = 0.5
	--sp_mid_04 = 0.5
	--sp_mid_06 = 0.5
	--sp_mid_05 = 10.0
	--sp_mid_01 = 0.5
	--sp_mid_02 = 0.5
	--sp_mid_03 = 0.5
	--sp_mid_04 = 0.5
	--sp_mid_05 = 6.0
	--sp_mid_06 = 8.0
	--sp_mid_01 = 0.5
	--sp_mid_02 = 0.5
	--sp_mid_04 = 2.0
	--sp_mid_03 = 8.0
	--sp_wave5_04 = 2.0
	--sp_wave5_04 = 12.0
	wave3loop = {10.0,
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_mid_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_mid_03,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_mid_02,
["aware"] = true,
["spawnFX"] = true,
["playSoundFX"] = true},
0.5,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_mid_04,
["aware"] = true,
["spawnFX"] = true},
0.5,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_mid_06,
["aware"] = true,
["spawnFX"] = true},
0.5,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_mid_05,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_mid_01,
["aware"] = true,
["spawnFX"] = true},
0.5,
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_mid_02,
["aware"] = true,
["spawnFX"] = true},
0.5,
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_mid_03,
["aware"] = true,
["spawnFX"] = true},
0.5,
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_mid_04,
["aware"] = true,
["spawnFX"] = true},
0.5,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_mid_05,
["aware"] = true,
["spawnFX"] = true},
6.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_mid_06,
["aware"] = true,
["spawnFX"] = true},
8.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_mid_01,
["aware"] = true,
["spawnFX"] = true},
0.5,
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_mid_02,
["aware"] = true,
["spawnFX"] = true},
0.5,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_mid_04,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_mid_05,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_mid_03,
["aware"] = true,
["spawnFX"] = true},
8.0,
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave5_04,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave5_04,
["aware"] = true,
["spawnFX"] = true},
12.0}
	--sp_mid_03 = 1.0
	--sp_mid_02 = 0.5
	--sp_mid_04 = 0.5
	--sp_mid_06 = 0.5
	--sp_wave3_02 = 1.0
	--sp_wave2_02 = 15.0
	wave5loop = {5.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave5_06,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_mid_03,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_mid_02,
["aware"] = true,
["spawnFX"] = true,
["playSoundFX"] = true},
0.5,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_mid_04,
["aware"] = true,
["spawnFX"] = true},
0.5,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_mid_06,
["aware"] = true,
["spawnFX"] = true},
0.5,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave3_02,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave2_02,
["aware"] = true,
["spawnFX"] = true},
15.0}
	--sp_wave1_05 = 2.0
	--sp_wave1_07 = 1.0
	--sp_wave1_01 = 0.5
	--sp_wave1_03 = 0.5
	--sp_wave2_06 = 0.5
	--sp_wave4_04 = 15.0
	wave5loopCenter = {5.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave1_05,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave1_06,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave1_07,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave1_01,
["aware"] = true,
["spawnFX"] = true},
0.5,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave1_03,
["aware"] = true,
["spawnFX"] = true},
0.5,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave2_06,
["aware"] = true,
["spawnFX"] = true},
0.5,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave4_04,
["aware"] = true,
["spawnFX"] = true},
15.0}
	--sp_north_01 = 2.0
	--sp_north_01 = 8.0
	--sp_north_01 = 2.0
	--sp_north_01 = 10.0
	--sp_north_02 = 2.0
	--sp_north_02 = 8.0
	--sp_north_02 = 10.0
	--sp_north_01 = 2.0
	--sp_north_02 = 10.0
	--sp_north_01 = 8.0
	--sp_wave1_03 = 1.0
	--sp_wave1_05 = 1.0
	--sp_wave1_04 = 1.0
	wave1 = {5.0,
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_north_01,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_north_01,
["aware"] = true,
["spawnFX"] = true,
["playSoundFX"] = true},
8.0,
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_north_01,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_north_01,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_north_02,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_north_02,
["aware"] = true,
["spawnFX"] = true},
8.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_north_02,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_north_01,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_north_02,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_north_02,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_north_01,
["aware"] = true,
["spawnFX"] = true},
8.0,
networkFunctions.ShowWayRight,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave1_03,
["aware"] = true,
["spawnFX"] = true},
1.0,
networkFunctions.StopShowWayRight,
8.0,
networkFunctions.ShowWayFront,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave1_05,
["aware"] = true,
["spawnFX"] = true},
1.0,
networkFunctions.StopShowWayFront,
8.0,
networkFunctions.ShowWayLeft,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
1.0,
networkFunctions.StopShowWayLeft}
	--sp_wave1_04 = 2.0
	--sp_wave1_04 = 4.0
	--sp_wave1_05 = 2.0
	--sp_wave1_01 = 2.0
	--sp_wave1_03 = 2.0
	--sp_wave1_05 = 4.0
	--sp_wave5_01 = 10.0
	--sp_wave1_04 = 1.0
	--sp_wave1_05 = 1.0
	--sp_wave1_03 = 2.0
	--sp_wave1_05 = 2.0
	--sp_wave1_05 = 10.0
	--sp_wave1_01 = 2.0
	wave2 = {10.0,
networkFunctions.ShowWayLeft,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true,
["playSoundFX"] = true},
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["challenge"] = challengeSet1,
["bonusPoints"] = 2500.0},
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
4.0,
networkFunctions.StopShowWayLeft,
networkFunctions.ShowWayFront,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave1_05,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave1_05,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave1_05,
["aware"] = true,
["spawnFX"] = true},
networkFunctions.StopShowWayFront,
10.0,
networkFunctions.ShowWayDownRight,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave1_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave1_01,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave1_01,
["aware"] = false,
["spawnFX"] = true},
networkFunctions.StopShowWayDownRight,
10.0,
networkFunctions.ShowWayRight,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave1_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave1_03,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave1_03,
["aware"] = false,
["spawnFX"] = true},
networkFunctions.StopShowWayRight,
4.0,
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave4_04,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5_01,
["aware"] = true,
["spawnFX"] = true},
10.0,
networkFunctions.ShowWayLeft,
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = false,
["spawnFX"] = true},
1.0,
networkFunctions.ShowWayFront,
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1_05,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_wave1_05,
["aware"] = false,
["spawnFX"] = true},
1.0,
networkFunctions.StopShowWayLeft,
networkFunctions.StopShowWayFront,
8.0,
networkFunctions.ShowWayRight,
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_wave1_03,
["aware"] = false,
["spawnFX"] = true},
2.0,
networkFunctions.StopShowWayRight,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave1_03,
["aware"] = true,
["spawnFX"] = true},
--nil,
10.0,
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_wave1_05,
["aware"] = false,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave1_05,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_wave1_01,
["aware"] = false,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave1_01,
["aware"] = true,
["spawnFX"] = true}}
	--wave3loop = 1.0
	wave3 = {10.0,
{["capturePoint"] = mkr_objective_01,
["awardPoints"] = 2500.0,
["waveBlocker"] = true,
["loopingSpawns"] = wave3loop,
["duration"] = 90.0,
["timeLimit"] = 140.0,
["loseAfterTimeOut"] = true},
1.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave1_01,
["aware"] = true}}
	--sp_wave1_04 = 5.0
	--sp_wave1_05 = 10.0
	--sp_wave1_05 = 8.0
	--sp_wave1_03 = 10.0
	--sp_wave3_03 = 8.0
	--sp_wave3_03 = 10.0
	--sp_wave4_04 = 10.0
	--sp_wave5_01 = 10.0
	--sp_wave1_04 = 2.0
	--challengeSet2 = 6.0
	--sp_wave3_03 = 6.0
	--sp_wave4_04 = 10.0
	--sp_wave5_01 = 6.0
	wave4 = {5.0,
networkFunctions.ShowWayRight,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true,
["playSoundFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
5.0,
networkFunctions.StopShowWayRight,
networkFunctions.ShowWayLeft,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave1_05,
["aware"] = true,
["spawnFX"] = true},
10.0,
networkFunctions.StopShowWayLeft,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave1_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave1_05,
["aware"] = true,
["spawnFX"] = true},
8.0,
networkFunctions.ShowWayFront,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1_05,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1_03,
["aware"] = true,
["spawnFX"] = true},
10.0,
networkFunctions.StopShowWayFront,
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true},
8.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave4_04,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave5_01,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5_04,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["challenge"] = challengeSet2,
["bonusPoints"] = 2500.0},
6.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true},
6.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave4_04,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave5_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave5_01,
["aware"] = true,
["spawnFX"] = true},
6.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true}}
	--sp_wave1_05 = 2.0
	--sp_wave1_05 = 8.0
	--sp_wave3_03 = 2.0
	--sp_wave1_04 = 2.0
	--sp_wave1_05 = 10.0
	--sp_wave1_04 = 10.0
	--sp_wave1_05 = 8.0
	--sp_wave3_03 = 1.0
	--wave5loop = 2.0
	--ls_captureTurretsFire = 1.0
	--sp_wave_after = 1.0
	--sp_wave1_far = 1.0
	--sp_wave5_03 = 2.0
	wave5 = {2.0,
networkFunctions.ShowWayFront,
networkFunctions.ShowWayLeft,
networkFunctions.ShowWayRight,
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave1_05,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["challenge"] = challengeSet3,
["bonusPoints"] = 2500.0},
networkFunctions.StopShowWayFront,
networkFunctions.StopShowWayLeft,
networkFunctions.StopShowWayRight,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true,
["playSoundFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1_05,
["aware"] = true,
["spawnFX"] = true},
8.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave1_05,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave1_05,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_wave5_06,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_wave5_04,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave1_05,
["aware"] = true,
["spawnFX"] = true},
8.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_wave5_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave1_04,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave3_03,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 2.0},
{["capturePoint"] = {mkr_objective_ActivateTurret01, mkr_objective_ActivateTurret02},
["awardPoints"] = 2000.0,
["waveBlocker"] = true,
["loopingSpawns"] = wave5loop,
["duration"] = 90.0,
["timeLimit"] = 200.0,
["loseAfterTimeOut"] = true},
2.0,
networkFunctions.AutomatedTurret_Enable01,
{["capturePoint"] = mkr_objective_ActivateTurret03,
["awardPoints"] = 3000.0,
["waveBlocker"] = true,
["loopingSpawns"] = wave5loopCenter,
["duration"] = 90.0,
["timeLimit"] = 140.0,
["loseAfterTimeOut"] = true,
["objectiveText"] = ls_captureTurretsFire},
1.0,
networkFunctions.AutomatedTurret_Shoot01,
2.0,
--nil,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave_after,
["aware"] = true,
["spawnFX"] = true,
["playSoundFX"] = true},
1.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave5_03,
["aware"] = true,
["spawnFX"] = true,
["playSoundFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave4_04,
["aware"] = true,
["spawnFX"] = true,
["playSoundFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1_far,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave4_03,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 10.0},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1,
["aware"] = true,
["spawnFX"] = true,
["playSoundFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave5_03,
["aware"] = true,
["spawnFX"] = true,
["playSoundFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1_far,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1,
["aware"] = true,
["spawnFX"] = true,
["playSoundFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave5_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave4_04,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave5_03,
["aware"] = true,
["spawnFX"] = true,
["playSoundFX"] = true},
2.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1,
["aware"] = true,
["spawnFX"] = true,
["playSoundFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave5_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave4_04,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1_far,
["aware"] = true,
["spawnFX"] = true}}
	networkFunctions.setTanksInvulnerable()
	COOP_RegisterWaves(wave1, wave2, wave3, wave4, wave5)
end

function MissionStart() --f_1
	COOP_StartWaves(trig_start)
	networkFunctions.AutomatedTurret_Disable01()
	COOP_SetOrkIgnoreGroup(grp_turret1)
	COOP_SetOrkIgnoreGroup(grp_turret2)
	COOP_SetOrkIgnoreGroup(grp_turret3)
	COOP_SetOrkIgnoreGroup(grp_turret4)
	COOP_SetOrkIgnoreGroup(grp_turret5)
	RegisterPlayerEvents()
end

function MissionComplete() --f_2

end

function OnCleanup() --f_3

end

networkFunctions.AutomatedTurret_Shoot01 = function ()
	local var0
	var0 = Coop_Audio2D(csp_turrets_firing)
	multiplayer.assets.csp_firing = var0
	csp_turrets_firing = 1.0
	Event_AddTimer(
	networkFunctions.playNextSpeech,
	csp_turrets_firing, true)
end

networkFunctions.AutomatedTurret_Enable01 = function ()
	Coop_Audio2D(csp_turrets_activated)
	AutomatedTurret_Enable(grp_turret1)
	AutomatedTurret_Enable(grp_turret2)
	AutomatedTurret_Enable(grp_turret3)
	AutomatedTurret_Enable(grp_turret4)
	AutomatedTurret_Enable(grp_turret5)
end

networkFunctions.AutomatedTurret_Disable01 = function ()
	print("AutomatedTurret_Disable01")
	AutomatedTurret_Disable(grp_turret1)
	AutomatedTurret_Disable(grp_turret2)
	AutomatedTurret_Disable(grp_turret3)
	AutomatedTurret_Disable(grp_turret4)
	AutomatedTurret_Disable(grp_turret5)
end

networkFunctions.playNextSpeech = function (arg0)
	local var0
	var0 = Audio_IsPlaying(multiplayer.assets.csp_firing)
	if not var0 then
			Coop_Audio2D(csp_turrets_firing_now)
			AutomatedTurret_Shoot(grp_turret1)
			AutomatedTurret_Shoot(grp_turret2)
			AutomatedTurret_Shoot(grp_turret3)
			AutomatedTurret_Shoot(grp_turret4)
			AutomatedTurret_Shoot(grp_turret5)
			Event_Remove(arg0)
	end
end

networkFunctions.ShowWayLeft = function () Marker_PlayFX(mkr_explosionWay_01_Left) end
networkFunctions.StopShowWayLeft = function () Marker_StopFX(mkr_explosionWay_01_Left) end
networkFunctions.ShowWayRight = function () Marker_PlayFX(mkr_explosionWay_01_Right) end
networkFunctions.StopShowWayRight = function () Marker_StopFX(mkr_explosionWay_01_Right) end
networkFunctions.ShowWayFront = function () Marker_PlayFX(mkr_explosionWay_01_Front) end
networkFunctions.StopShowWayFront = function () Marker_StopFX(mkr_explosionWay_01_Front) end
networkFunctions.ShowWayDownRight = function () Marker_PlayFX(mkr_explosionWay_01_DownRight) end
networkFunctions.StopShowWayDownRight = function () Marker_StopFX(mkr_explosionWay_01_DownRight) end
networkFunctions.setTanksInvulnerable = function () 
print("setTanksInvulnerable")
Coop_SetInvulnerable(grp_tanks, true) 
end