require("Util/Common")
require("Util/MissionTask")
require("Util/CP/CP_Common")
require("Util/CP/CP_Func")

multiplayer.objectiveData = {}
chaosMission = true
arenaNum = 1.0
thisArena = "CP_Arena_desert_c"
arenaExit = "mkr_desert_c_exit"
nextArena = "cp_arena_habs_e"
nextArenaEnter = "mkr_habs_e_entrance"

function MissionStartNetwork() --f_0
	InitLuaSafe()
	
	challengeSet1 = {{["challengeType"] = ch_speedKill,
["timeLimit"] = 25.0,
["targetAmount"] = 20.0},
{["challengeType"] = ch_selectiveKill,
["timeLimit"] = 20.0,
["targetAmount"] = 15.0,
["unitType"] = cp_ork_gretchin},
{["challengeType"] = ch_ballHog,
["timeLimit"] = 25.0,
["targetAmount"] = 8.0},
{["challengeType"] = ch_sychronizedKill,
["timeLimit"] = 20.0,
["targetAmount"] = 10.0},
{["challengeType"] = ch_multiMegaKill,
["timeLimit"] = 25.0,
["targetAmount"] = 3.0}}
	challengeSet2 = {{["challengeType"] = ch_speedKill,
["timeLimit"] = 20.0,
["targetAmount"] = 15.0},
{["challengeType"] = ch_selectiveKill,
["timeLimit"] = 20.0,
["targetAmount"] = 8.0,
["unitType"] = cp_ork_boy_ranged},
{["challengeType"] = ch_ballHog,
["timeLimit"] = 20.0,
["targetAmount"] = 8.0},
{["challengeType"] = ch_sychronizedKill,
["timeLimit"] = 20.0,
["targetAmount"] = 10.0},
{["challengeType"] = ch_multiMegaKill,
["timeLimit"] = 25.0,
["targetAmount"] = 3.0}}
	challengeSet3 = {{["challengeType"] = ch_speedKill,
["timeLimit"] = 20.0,
["targetAmount"] = 15.0},
{["challengeType"] = ch_selectiveKill,
["timeLimit"] = 20.0,
["targetAmount"] = 4.0,
["unitType"] = cp_ork_boy_melee_pro},
{["challengeType"] = ch_ballHog,
["timeLimit"] = 20.0,
["targetAmount"] = 6.0},
{["challengeType"] = ch_sychronizedKill,
["timeLimit"] = 20.0,
["targetAmount"] = 8.0},
{["challengeType"] = ch_multiMegaKill,
["timeLimit"] = 20.0,
["targetAmount"] = 3.0}}
	sp_north = {sp_wave3_01,
sp_wave1_04,
sp_wave1_08,
sp_wave3_08}
	sp_south = {sp_wave2_07,
sp_wave2_05,
sp_wave2_01,
sp_wave2_02}
	sp_wave1_ork = COOP_GetSpawnPointGroup("sp_wave1_ork")
	sp_wave1_ig = COOP_GetSpawnPointGroup("sp_wave1_ig")
	sp_wave3_ork = COOP_GetSpawnPointGroup("sp_wave3_ork")
	sp_wave3_ig = COOP_GetSpawnPointGroup("sp_wave3_ig")
	sp_wave4_ig = COOP_GetSpawnPointGroup("sp_wave4_ig")
	sp_wave4_psyker = COOP_GetSpawnPointGroup("sp_wave4_psyker")
	-- sp_wave2_01 = "grp_spawn"
	-- sp_wave2_02 = "grp_spawn"
	-- mkr_challengeCP_07 = "grp_spawn"
	spawnLoop01 = {{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_north,
["aware"] = true,
["groups"] = {"grp_spawn"},
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_south,
["aware"] = true,
["groups"] = {"grp_spawn"},
["spawnFX"] = true},
5.0,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_north,
["aware"] = true,
["groups"] = {"grp_spawn"},
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_north,
["aware"] = true,
["groups"] = {"grp_spawn"},
["spawnFX"] = true},
5.0,
{["ebp"] = cp_guard_guardsman_grenade_launcher,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_north,
["aware"] = true,
["spawnFX"] = true,
["groups"] = {"grp_spawn"}},
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_south,
["aware"] = true,
["spawnFX"] = true,
["groups"] = {"grp_spawn"}},
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_north,
["aware"] = true,
["spawnFX"] = true,
["groups"] = {"grp_spawn"}},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_south,
["aware"] = true,
["groups"] = {"grp_spawn"},
["spawnFX"] = true},
20.0}
	--sp_wave4_ig = 10.0
	--sp_wave4_ig = 15.0
	--sp_wave4_psyker = 5.0
	--sp_wave4_psyker = 20.0
	spawnLoop02 = {{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave4_ig,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave4_ig,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave4_ig,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave4_ig,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave4_ig,
["aware"] = true,
["spawnFX"] = true},
15.0,
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave4_psyker,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_grenade_launcher,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave4_psyker,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave4_psyker,
["aware"] = true,
["spawnFX"] = true},
20.0}
	--mkr_wave1_orkgoto_01 = 15.0
	--sp_wave1_ork = 15.0
	--sp_wave1_ig = 15.0
	wave1 = {{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave1_ork,
["goto"] = mkr_wave1_orkgoto_01,
["spawnFX"] = true,
["playSoundFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 7.0,
["spawnPoints"] = sp_wave1_ig_01,
["hold"] = mkr_DefendExit_01},
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave1_ork,
["goto"] = mkr_wave1_orkgoto_01,
["spawnFX"] = true,
["playSoundFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 7.0,
["spawnPoints"] = sp_wave1_ig_02,
["hold"] = mkr_DefendExit_05},
{["leftAlive"] = 15.0},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave1_ork,
["goto"] = mkr_wave1_orkgoto_01,
["spawnFX"] = true},
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 13.0,
["spawnPoints"] = sp_wave1_ork,
["goto"] = mkr_wave1_orkgoto_01,
["spawnFX"] = true},
15.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1_ork,
["spawnFX"] = true},
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 11.0,
["spawnPoints"] = sp_wave1_ork,
["spawnFX"] = true},
{["leftAlive"] = 15.0},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_wave1_ork,
["spawnFX"] = true},
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 9.0,
["spawnPoints"] = sp_wave1_ork,
["spawnFX"] = true},
15.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 7.0,
["spawnPoints"] = sp_wave1_ork,
["spawnFX"] = true},
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave1_ork,
["spawnFX"] = true},
{["leftAlive"] = 5.0},
{["challenge"] = challengeSet1,
["bonusPoints"] = 1500.0},
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 16.0,
["spawnPoints"] = sp_wave1_ork,
["goto"] = mkr_wave1_orkgoto_01,
["spawnFX"] = true,
["playSoundFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1_ig_01,
["hold"] = mkr_DefendExit_01},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1_ig_02,
["hold"] = mkr_DefendExit_05},
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave1_ig},
15.0,
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 20.0,
["spawnPoints"] = sp_wave1_ork,
["goto"] = mkr_wave1_orkgoto_01,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave1_ig_01,
["hold"] = mkr_DefendExit_01},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave1_ig_02,
["hold"] = mkr_DefendExit_05},
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave1_ig},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_wave1_ork,
["goto"] = mkr_wave1_orkgoto_01,
["spawnFX"] = true}}
	--sp_wave2_psyker_01 = 2.0
	--sp_wave2_psyker_01 = 10.0
	--sp_wave2_psyker_02 = 2.0
	--sp_wave2_psyker_02 = 5.0
	--sp_wave2_psyker_03 = 2.0
	--sp_wave2_psyker_01 = 2.0
	--sp_wave2_psyker_01 = 7.0
	--sp_wave2_psyker_02 = 3.0
	--sp_wave2_psyker_01 = 6.0

	wave2 = {{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave2_psyker_01,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave2_psyker_01,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave2_psyker_02,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave2_psyker_02,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave2_psyker_03,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave2_psyker_03,
["spawnFX"] = true},
{["leftAlive"] = 8.0},
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave2_psyker_01,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave2_psyker_01,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave2_psyker_01,
["spawnFX"] = true},
7.0,
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave2_psyker_02,
["spawnFX"] = true},
3.0,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave2_psyker_02,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave2_psyker_01,
["spawnFX"] = true},
6.0,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave2_psyker_03,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave2_psyker_01,
["spawnFX"] = true}}

	--sp_wave3_ork = 15.0
	--sp_wave3_ork = 15.0
	wave3 = {{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 7.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_wave3_ork,
["spawnFX"] = true},
15.0,
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 7.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave3_ork,
["spawnFX"] = true},
{["leftAlive"] = 10.0},
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_ork,
["spawnFX"] = true},
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_wave3_ork,
["spawnFX"] = true},
15.0,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_ork,
["spawnFX"] = true},
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave3_ork,
["spawnFX"] = true},
{["leftAlive"] = 10.0},
{["challenge"] = challengeSet2,
["bonusPoints"] = 1500.0},
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_wave3_ork,
["spawnFX"] = true},
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 13.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true}}

	wave4 = {5.0,
{["capturePoint"] = mkr_capture_04,
["awardPoints"] = 2000.0,
["waveBlocker"] = true,
["loopingSpawns"] = spawnLoop02,
["duration"] = 90.0,
["timeLimit"] = 240.0,
["loseAfterTimeOut"] = true},
1.0,
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true}}

	--sp_wave3_ig = 15.0
	--sp_wave3_ork = 15.0
	wave5 = {{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave3_ork,
["spawnFX"] = true},
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 7.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true},
15.0,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave3_ork,
["spawnFX"] = true},
{["leftAlive"] = 10.0},
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_wave3_ork,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_wave3_ork,
["spawnFX"] = true},
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_wave3_ork,
["spawnFX"] = true},
15.0,
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_ork,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_ork,
["spawnFX"] = true},
{["ebp"] = cp_ork_gretchin,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave3_ork,
["spawnFX"] = true},
{["challenge"] = challengeSet3,
["bonusPoints"] = 1500.0},
{["leftAlive"] = 10.0},
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true},
{["leftAlive"] = 5.0},
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave3_ig,
["spawnFX"] = true}}

	COOP_RegisterWaves(wave1, wave2, wave3, wave4, wave5)
end

function MissionStart() --f_1
	COOP_StartWaves(trig_start)
	RegisterPlayerEvents()
end