require("Util/Common")
require("Util/MissionTask")
require("Util/CP/CP_Common")
require("Util/CP/CP_Func")

multiplayer.objectiveData = {}
chaosMission = true
arenaNum = 4.0
thisArena = "CP_Arena_waterworks"
arenaExit = "mkr_waterworks_exit"

function MissionStartNetwork()
	InitLuaSafe()
	
	sp_wave1_ig = {sp_wave1_03,
sp_wbWave_01,
sp_wbWave_07, sp_wbWave_02}
	sp_wave2_ig = {sp_wbWave_03,
sp_wbWave_05, sp_wave2_01}
	sp_wave3_ork = {sp_wave3_01,
sp_wbWave_04, sp_wbWave_03}
	sp_wave3_ork2 = {sp_wave3_01,
sp_wbWave_04,
sp_wbWave_03, sp_wbWave_05}
	sp_wave3_ork3 = {sp_wbWave_04,
sp_wbWave_03,
sp_wbWave_05, sp_wave1_01}
	sp_wave3_ork4 = {sp_wbWave_03,
sp_wbWave_05,
sp_wave1_01, sp_wbWave_08}
	sp_wave4_ork = {sp_wave3_01,
sp_wbWave_04, sp_wbWave_03}
	sp_wave4_ork2 = {sp_wbWave_08,
sp_wbWave_02, sp_wbWave_07}
	sp_wave5_ork = {sp_wave3_01,
sp_wbWave_08, sp_wbWave_07}
	sp_wave5_ork2 = {sp_wave3_01,
sp_wbWave_08,
sp_wbWave_07, sp_wave1_01}
	sp_wave5_ork3 = {sp_wave1_03,
sp_wbWave_08,
sp_wbWave_07, sp_wave1_01}
	sp_wave5_ork4 = {sp_wave1_03,
sp_wbWave_08,
sp_wbWave_07,
sp_wave1_01, sp_wbWave_05}

	sp_wave1_ork = COOP_GetSpawnPointGroup("sp_wave1_ork")
	sp_wbWave = COOP_GetSpawnPointGroup("sp_wbWave")

	sp_wbWave1 = {sp_wbWave_01,
sp_wbWave_02,
sp_wbWave_05,
sp_wbWave_06,
sp_wbWave_07,
sp_wbWave_08}
	sp_wbWave2 = {sp_wbWave_02,
sp_wbWave_03,
sp_wbWave_04,
sp_wbWave_07,
sp_wbWave_08}
	sp_wbWave3 = {sp_wbWave_01,
sp_wbWave_03,
sp_wbWave_04,
sp_wbWave_05,
sp_wbWave_06}

	challengeSet1 = {{["challengeType"] = ch_speedKill,
["timeLimit"] = 15.0,
["targetAmount"] = 12.0},
{["challengeType"] = ch_kingOfTheHill,
["timeLimit"] = 12.0,
["markers"] = {mkr_challengeCP_01},
["captureTime"] = 2.0},
{["challengeType"] = ch_ballHog,
["timeLimit"] = 15.0,
["targetAmount"] = 8.0},
{["challengeType"] = ch_sychronizedKill,
["timeLimit"] = 15.0,
["targetAmount"] = 10.0}}
	challengeSet2 = {{["challengeType"] = ch_speedKill,
["timeLimit"] = 15.0,
["targetAmount"] = 12.0},
{["challengeType"] = ch_kingOfTheHill,
["timeLimit"] = 10.0,
["markers"] = {mkr_challengeCP_03},
["captureTime"] = 2.0},
{["challengeType"] = ch_selectiveKill,
["timeLimit"] = 15.0,
["targetAmount"] = 5.0,
["unitType"] = cp_ork_hardboy},
{["challengeType"] = ch_ballHog,
["timeLimit"] = 15.0,
["targetAmount"] = 8.0},
{["challengeType"] = ch_sychronizedKill,
["timeLimit"] = 15.0,
["targetAmount"] = 10.0}}
	challengeSet3 = {{["challengeType"] = ch_speedKill,
["timeLimit"] = 15.0,
["targetAmount"] = 7.0},
{["challengeType"] = ch_kingOfTheHill,
["timeLimit"] = 10.0,
["markers"] = {mkr_challengeCP_05},
["captureTime"] = 2.0},
{["challengeType"] = ch_ballHog,
["timeLimit"] = 15.0,
["targetAmount"] = 4.0},
{["challengeType"] = ch_sychronizedKill,
["timeLimit"] = 25.0,
["targetAmount"] = 5.0}}

	--sp_wave1_03 = 5.0
	--sp_wave1_ig = 10.0
	--sp_wave1_ig = 6.0
	--sp_wave1_ig = 6.0
	--sp_wave1_ig = 4.0
	--sp_wave1_ig = 6.0
	--sp_wave1_ig = 4.0
	--sp_wave1_ig = 6.0
	--sp_wave1_ig = 4.0
	wave1 = {{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave1_ork,
["goto"] = sp_wbWave_08,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave1_ig,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave1_ork,
["goto"] = sp_wbWave_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave1_03,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave1_ork,
["goto"] = sp_wbWave_05,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave_02,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave1_ig,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave1_ork,
["goto"] = sp_wbWave_08,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave1_ig,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave1_ork,
["goto"] = sp_wbWave_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave1_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave1_ork,
["goto"] = sp_wbWave_05,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave1_ig,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 12.0},
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave_02,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 9.0,
["spawnPoints"] = sp_wave1_ig,
["aware"] = true,
["spawnFX"] = true},
6.0,
{["ebp"] = cp_guard_guardsman_grenade_launcher,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave1_ig,
["aware"] = true,
["spawnFX"] = true},
6.0,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_wave1_ig,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 12.0},
{["challenge"] = challengeSet1,
["bonusPoints"] = 2500.0},
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave_02,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave1_03,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave1_ig,
["aware"] = true,
["spawnFX"] = true},
4.0,
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave1_ig,
["aware"] = true,
["spawnFX"] = true},
6.0,
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave1_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave1_ig,
["aware"] = true,
["spawnFX"] = true},
4.0,
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave1_ig,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 15.0},
{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave_02,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 9.0,
["spawnPoints"] = sp_wave1_ig,
["aware"] = true,
["spawnFX"] = true},
6.0,
{["ebp"] = cp_guard_guardsman_grenade_launcher,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave1_ig,
["aware"] = true,
["spawnFX"] = true},
4.0,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_wave1_ig,
["aware"] = true,
["spawnFX"] = true}}

	--sp_wave2_ig = 5.0
	--sp_wave2_ig = 5.0
	--sp_wave2_ig = 10.0
	--sp_wave2_ig = 5.0
	--sp_wave2_ig = 12.0
	--sp_wave2_ig = 15.0
	wave2_loop = {{["ebp"] = cp_guard_psyker,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave2_ig,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave2_ig,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_wave2_ig,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_grenade_launcher,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave2_ig,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave2_ig,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 7.0,
["spawnPoints"] = sp_wave2_ig,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave2_ig,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_shotgun,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave2_ig,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave2_ig,
["aware"] = true,
["spawnFX"] = true},
12.0,
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave2_ig,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave2_ig,
["spawnFX"] = true},
15.0}

	wave2 = {5.0,
{["capturePoint"] = mkr_cp_01,
["awardPoints"] = 2500.0,
["waveBlocker"] = true,
["loopingSpawns"] = wave2_loop,
["duration"] = 120.0,
["timeLimit"] = 180.0,
["loseAfterTimeOut"] = true},
1.0,
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave2_ig,
["aware"] = true,
["spawnFX"] = true}}

	--sp_wave1_ork_01 = 10.0
	--sp_wave3_ork = 10.0
	--sp_wave3_ork2 = 5.0
	--sp_wave3_ork2 = 5.0
	--sp_wave3_ork3 = 15.0
	--sp_wave3_ork3 = 8.0
	--sp_wave3_ork4 = 10.0
	--sp_wave3_ork4 = 10.0
	--sp_wave3_ork4 = 12.0
	wave3 = {{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_wave3_ork,
["goto"] = sp_wave1_ork_01,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman_chainsword,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave1_ork_01,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_ork,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_wave3_ork,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_ork,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_wave3_ork,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 12.0},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave3_ork2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave3_ork2,
["goto"] = mkr_left_02,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_ork2,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_ork2,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 17.0},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_ork2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave3_ork2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave3_ork2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave3_ork2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave3_ork2,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_ork2,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 13.0},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_ork3,
["aware"] = false,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave3_ork3,
["aware"] = false,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave3_ork3,
["aware"] = false,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_ork3,
["aware"] = false,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave3_ork3,
["aware"] = false,
["spawnFX"] = true},
{["leftAlive"] = 18.0},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_ork3,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_ork3,
["aware"] = true,
["spawnFX"] = true},
15.0,
{["challenge"] = challengeSet2,
["bonusPoints"] = 2500.0},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave3_ork3,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave3_ork3,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_wave3_ork3,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee,
["unitAmount"] = 10.0,
["spawnPoints"] = sp_wave3_ork3,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 17.0},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave3_ork3,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave3_ork3,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_ork3,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_ork3,
["aware"] = true,
["spawnFX"] = true},
8.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_ork3,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_ork3,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 17.0},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave3_ork4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_ork4,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave3_ork4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave3_ork4,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave3_ork4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave3_ork4,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 20.0},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_ork4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave3_ork4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave3_ork4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave3_ork4,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 17.0},
12.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave3_ork4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wave3_ork4,
["aware"] = true,
["spawnFX"] = true},
12.0,
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_ork4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_ork4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave3_ork4,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 22.0},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_ork4,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave3_ork4,
["aware"] = true,
["spawnFX"] = true}}
	--sp_wave4_ork = 5.0
	--sp_wave4_ork = 10.0
	--sp_wave4_ork = 5.0
	--sp_wave4_ork = 10.0
	--sp_wave4_ork = 6.0
	--sp_wave4_ork2 = 12.0
	--sp_wave4_ork2 = 12.0
	--sp_wave4_ork = 6.0
	--sp_wave4_ork2 = 12.0
	--sp_wave4_ork = 6.0
	--sp_wave4_ork = 12.0
	--sp_wave4_ork2 = 12.0
	--sp_wave4_ork = 5.0
	--sp_wave4_ork2 = 20.0
	wave4_loop = {{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave4_ork,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wave4_ork,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave4_ork2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave4_ork,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave4_ork,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave4_ork,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave4_ork2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave4_ork,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave4_ork,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave4_ork,
["aware"] = true,
["spawnFX"] = true},
6.0,
{["ebp"] = cp_ork_boy_ranged_grenade,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wave4_ork2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave4_ork2,
["aware"] = true,
["spawnFX"] = true},
12.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave4_ork,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave4_ork2,
["aware"] = true,
["spawnFX"] = true},
12.0,
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave4_ork,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave4_ork,
["aware"] = true,
["spawnFX"] = true},
6.0,
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave4_ork2,
["aware"] = true,
["spawnFX"] = true},
12.0,
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave4_ork2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave4_ork,
["aware"] = true,
["spawnFX"] = true},
6.0,
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave4_ork2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave4_ork,
["aware"] = true,
["spawnFX"] = true},
12.0,
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave4_ork,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wave4_ork2,
["aware"] = true,
["spawnFX"] = true},
12.0,
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave4_ork,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave4_ork,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave4_ork2,
["aware"] = true,
["spawnFX"] = true},
20.0}

	wave4 = {
	{["capturePoint"] = mkr_cp_03,
	["awardPoints"] = 2500.0,
	["waveBlocker"] = true,
	["loopingSpawns"] = wave4_loop,
	["duration"] = 120.0,
	["timeLimit"] = 180.0,
	["loseAfterTimeOut"] = true},
	1.0,
	{["ebp"] = cp_ork_boy_melee,
	["unitAmount"] = 1.0,
	["spawnPoints"] = sp_wave4_ork2,
	["aware"] = true}}

	--sp_wave5_ork = 8.0
	--sp_wave5_ork = 1.0
	--sp_wave5_ork2 = 1.0
	--sp_wave5_ork2 = 1.0
	--sp_wave5_ork2 = 2.0
	--sp_wave5_ork2 = 1.0
	--sp_wave5_ork2 = 1.0
	--sp_wave5_ork3 = 1.0
	--sp_wave5_ork3 = 10.0
	--sp_wave5_ork3 = 1.0
	--sp_wave5_ork3 = 3.0
	--sp_wave5_ork4 = 1.0
	--sp_wave5_ork4 = 1.0
	--sp_wave5_ork4 = 1.0
	--sp_wave5_ork4 = 5.0
	--sp_wave5_ork4 = 2.0
	wave5 = {{["ebp"] = cp_guard_psyker,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5_ork,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_guard_guardsman,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_wave5_ork,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_ork,
["aware"] = true,
["spawnFX"] = true},
8.0,
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_ork,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5_ork,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 7.0},
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_ork2,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_ork2,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_ork2,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5_ork2,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 6.0},
1.0,
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_ork2,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_ork2,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_ork2,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 7.0},
{["challenge"] = challengeSet3,
["bonusPoints"] = 2500.0},
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_ork3,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_ork3,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_ork3,
["aware"] = true,
["spawnFX"] = true},
10.0,
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_ork3,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_sm_bolter,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5_ork3,
["aware"] = true,
["spawnFX"] = true},
3.0,
{["ebp"] = cp_sm_dev_pc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5_ork3,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 8.0},
1.0,
{["ebp"] = cp_sm_chainsword,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5_ork4,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_sm_dev_lc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5_ork4,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 9.0},
{["ebp"] = cp_sm_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_ork4,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_sm_dev_lc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5_ork4,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 10.0},
{["ebp"] = cp_sm_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wave5_ork4,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_sm_dev_pc,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5_ork4,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_sm_melee,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5_ork4,
["aware"] = true,
["spawnFX"] = true},
2.0,
{["ebp"] = cp_sm_melee,
["unitAmount"] = 2.0,
["spawnPoints"] = sp_wave5_ork4,
["aware"] = true,
["spawnFX"] = true}}

	wave6 = {{["ebp"] = cp_ork_killa_kan,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_warboss_01,
["spawnFX"] = true,
["groups"] = {"grp_warboss"}},
0.5,
{["group"] = "grp_warboss",
["groupHealth"] = 0.75},
2.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wbWave,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wbWave,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 7.0,
["spawnPoints"] = sp_wbWave,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 7.0,
["spawnPoints"] = sp_wbWave,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_killa_kan,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_warboss_01,
["spawnFX"] = true,
["groups"] = {"grp_warboss"}},
{["leftAlive"] = 10.0},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wbWave,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wbWave,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 7.0,
["spawnPoints"] = sp_wbWave,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 7.0,
["spawnPoints"] = sp_wbWave,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["leftAlive"] = 15.0},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wbWave,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wbWave,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 7.0,
["spawnPoints"] = sp_wbWave,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_boy_melee_pro,
["unitAmount"] = 7.0,
["spawnPoints"] = sp_wbWave,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["leftAlive"] = 10.0},
{["groupHealth"] = 0.25,
["group"] = "grp_warboss"},
{["ebp"] = cp_ork_killa_kan,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_warboss_01,
["spawnFX"] = true,
["groups"] = {"grp_warboss"}},
10.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wbWave,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 6.0,
["spawnPoints"] = sp_wbWave1,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wbWave,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wbWave1,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wbWave1,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 10.0},
{["ebp"] = cp_ork_killa_kan,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_warboss_01,
["spawnFX"] = true,
["groups"] = {"grp_warboss"}},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wbWave,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wbWave1,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wbWave1,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wbWave,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wbWave1,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wbWave1,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 15.0},
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wbWave,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wbWave1,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_boy_ranged_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wbWave,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_hardboy,
["unitAmount"] = 5.0,
["spawnPoints"] = sp_wbWave1,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wbWave1,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 10.0},
{["group"] = "grp_warboss",
["groupHealth"] = 0.5},
{["ebp"] = cp_ork_killa_kan,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_warboss_01,
["spawnFX"] = true,
["groups"] = {"grp_warboss"}},
{["ebp"] = cp_ork_nob_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_ork_nob_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_nob_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_ork_nob_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_ork_nob_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 10.0},
{["ebp"] = cp_ork_killa_kan,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_warboss_01,
["spawnFX"] = true,
["groups"] = {"grp_warboss"}},
{["ebp"] = cp_ork_nob_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_ork_nob_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_nob_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_ork_nob_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_ork_nob_melee,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
3.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 10.0},
{["groupHealth"] = 0.5,
["group"] = "grp_warboss"},
{["ebp"] = cp_ork_killa_kan,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_warboss_01,
["spawnFX"] = true,
["groups"] = {"grp_warboss"}},
6.0,
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wbWave3,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_killa_kan,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_warboss_01,
["spawnFX"] = true,
["groups"] = {"grp_warboss"}},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wbWave3,
["aware"] = true,
["spawnFX"] = true},
{["leftAlive"] = 10.0},
{["groupHealth"] = 0.5,
["group"] = "grp_warboss"},
{["ebp"] = cp_ork_killa_kan,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_warboss_01,
["spawnFX"] = true,
["groups"] = {"grp_warboss"}},
6.0,
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
1.0,
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_wbWave2,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wbWave3,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_killa_kan,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_warboss_01,
["spawnFX"] = true,
["groups"] = {"grp_warboss"}},
{["ebp"] = cp_ork_nob_shoota_pro,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wbWave3,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_nob_melee_pro,
["unitAmount"] = 3.0,
["spawnPoints"] = sp_wbWave3,
["aware"] = true,
["spawnFX"] = true},
3.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 4.0,
["spawnPoints"] = sp_wbWave3,
["aware"] = true,
["spawnFX"] = true},
5.0,
{["ebp"] = cp_ork_squig_bomb,
["unitAmount"] = 8.0,
["spawnPoints"] = sp_wbWave3,
["aware"] = true,
["spawnFX"] = true},
{["ebp"] = cp_ork_killa_kan,
["unitAmount"] = 1.0,
["spawnPoints"] = sp_warboss_01,
["spawnFX"] = true,
["groups"] = {"grp_warboss"}}}

	COOP_RegisterWaves(wave1, wave2, wave3, wave4, wave5, wave6)
end

--multiplayer.assets.grp_warboss = 4.0

function MissionStart() --f_1
	multiplayer.assets.grp_warboss = Group_Create("grp_warboss")
	Event_AddNavMeshAreaExit(networkFunctions.killaKanHolder, multiplayer.assets.grp_warboss, "killaKanArea", ANY)
	COOP_StartWaves(trig_arenaStart)
	RegisterPlayerEvents()
end

networkFunctions.killaKanHolder = function (arg0, arg1, arg2, arg3, arg4) --f_2
	local var0 = Group_Create("")
	Group_Add(var0, arg4)
	Cmd_Move(var0, mkr_warboss_hold)
	Event_AddMarkerEnter(networkFunctions.releaseKillKan, var0, mkr_warboss_release, ANY)
end

networkFunctions.releaseKillKan = function (arg0, arg1, arg2, arg3) --f_3
	Cmd_Stop(arg1)
	Group_Clear(arg1)
	Group_Dealloc(arg1)
	Event_Remove(arg0)
end

networkFunctions.setWarbossInvincible70 = function () --f_4
	Coop_SetInvulnerable(multiplayer.assets.grp_warboss, 0.699999988079071)
end

networkFunctions.setWarbossInvincible45 = function () --f_5
	Coop_SetInvulnerable(multiplayer.assets.grp_warboss, 0.44999998807907104)
end

networkFunctions.setWarbossInvincible20 = function () --f_6
	Coop_SetInvulnerable(multiplayer.assets.grp_warboss, 0.20000000298023224)
end

networkFunctions.setWarbossInvincible0 = function () --f_7
	Coop_SetInvulnerable(multiplayer.assets.grp_warboss, false)
end